name = "sportslabanalytics"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
SUPABASE_URL = "https://vobiffgwkchogqklwlkp.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_rcpld30f243ZbHueuiL3lw_Gxtw-S_8"

[assets]
binding = "ASSETS"
directory = "./"
